### ISSUE TITLE
error connecting to db 

### ISSUE THREAD

**Issue by Thordekk** [BAndysc/WoWDatabaseEditor#110]
**Describe the bug**
Appear a message error in shadowlands tc

**Version (commit hash)**
last commit up to date

**To Reproduce**
open wowdbeditor, add db settings 

**Screenshots**
https://gyazo.com/2e553557070352bb69a2103c7ae24a5d

**Comment by BAndysc** [comment]
Thanks, fixed in https://github.com/BAndysc/WoWDatabaseEditor/commit/9db66157bd8650fec6be4a5005445fa7c0df38e5
