### ISSUE TITLE
"help wanted" AvaloniaGraph is not loaded in project While compiling

### ISSUE THREAD

**Issue by Abd-ulRahman** [BAndysc/WoWDatabaseEditor#115]
**Describe the bug**
I had to Remove it to have it compiled

**Version (commit hash)**
latest
commit e25b94baf64fc8651d6d7f7e8bc47588d6283bfa

**Comment by ncyellow** [comment]
This combination worked for me
1.  dotnet restore .\WowDatabaseEditor.sln
2.  add existing project AvalonGraph to solution

**Comment by niaro-kitty** [comment]
This combination worked for me

1. dotnet restore .\WowDatabaseEditor.sln
2. add existing project AvalonGraph to solution

**Comment by Abd-ulRahman** [comment]
> This combination worked for me
> 
>     1. dotnet restore .\WowDatabaseEditor.sln
> 
>     2. add existing project AvalonGraph to solution

Thanks
