### ISSUE TITLE
Add action give killed monster credit crashes editor

### ISSUE THREAD

**Issue by DuelistRag3** [BAndysc/WoWDatabaseEditor#12]
Whenever i try to add the action "Give killed monster credit" the editor just closes down

**Comment by BAndysc** [comment]
Hey, are you using latest version downloaded from AppVeyor (link in the readme) form here: https://ci.appveyor.com/api/projects/BAndysc/wowdatabaseeditor/artifacts/WoWDatabaseEditor.zip?branch=master?

**Comment by DuelistRag3** [comment]
yes i did, even today loaded the newest version

**Comment by DuelistRag3** [comment]
[Here is a gif of the problem](https://gyazo.com/4a078f3d316c1c72926563b5ed901d61)

**Comment by BAndysc** [comment]
Thank you for gif, indeed it crashes if source is other than none/self. I was testing it with „self” source only.

Could you please download latest build from AppVeyor and test it again?

**Comment by DuelistRag3** [comment]
fixed with e0102cd
