### ISSUE TITLE
A way to edit the database structures so we can work with old or custom dbs

### ISSUE THREAD

**Issue by LordArcanine** [BAndysc/WoWDatabaseEditor#121]
**Is your feature request related to a problem? Please describe.**
Yeha, im using a old tc db based on uwow leak for legion and i cant find a good wow database editor

**Describe the solution you'd like**
i want to propose a function in your database editor that can help all db developers to work on his dbs to make this database editor the most used one and the best one

**Additional context**

**Comment by BAndysc** [comment]
Only open source actively supported cores: TrinityCore and AzerothCore are supported. I advice contributing to those
