### ISSUE TITLE
Timed Events not available

### ISSUE THREAD

**Issue by gonzo1247** [BAndysc/WoWDatabaseEditor#14]
Follow Actions not available:

`SMART_ACTION_CREATE_TIMED_EVENT`
`SMART_ACTION_REMOVE_TIMED_EVENT`
`SMART_ACTION_CALL_TIMED_ACTIONLIST`
![timed_list01](https://user-images.githubusercontent.com/640311/105941182-25f57380-605d-11eb-96af-9c0f9e22bd2f.jpg)
![timed_list02](https://user-images.githubusercontent.com/640311/105941184-2726a080-605d-11eb-80a4-4a452662cf31.jpg)

**Comment by BAndysc** [comment]
They are available if you choose "NONE" source, because those actions do not have source.

However, I will probably also make them upper under "SELF"  source, as it is more natural to write

**Comment by BAndysc** [comment]
Updated behaviour in https://github.com/BAndysc/WoWDatabaseEditor/commit/74e6cf0bd31e44ae82029e8543dedf0d876fad59. Now actions with implicit NONE source (those are majority „script” related actions, without any source/target) are visible also if you pick source SELF.
