### ISSUE TITLE
Asking for support for our project

### ISSUE THREAD

**Issue by ProjectNighthold** [BAndysc/WoWDatabaseEditor#143]
Hi, my name is robert, im a dev from a new project called Project Nighthold, we went public and open source some days ago.

We want to create a free project for legion and want to work with you guys.

Someone has told me that you support only open-source projects and we want to see a way to work with you guys :P

Thanks in advance.

**Comment by BAndysc** [comment]
Welcome Robert, I don't have enough time to add support for another core, but if you want to do it, I will provide all the required help (and if you do it, it can be of course merged to the repo), feel free to contact me: bandysc#5087

**Comment by BAndysc** [comment]
I can see the project repo is (temporarily?) deleted, so I am closing the issue for now.

**Comment by ProjectNighthold** [comment]
we put for some weeks the repo as private, we need to get some devs for it, ill contact you when i get more devs :P
