### ISSUE TITLE
LAst trinitycore database parsing 

### ISSUE THREAD

**Issue by Thordekk** [BAndysc/WoWDatabaseEditor#144]
**Describe the bug**
I was getting sniff data and dont open any sniff appear as emppty, maybe is a parser issue, program parse one sniff then y try more or the same file and not work 

**Version (commit hash)**
Version Downloaded just now 

**To Reproduce**
1. Go to sniff open one file 
2. Click on creature text diff or gossip 
3.  If u can get data check with other sniff 
4. See error, only work one time to get text or sniff data if i want to use i have to download all again and i can open other file

**Comment by BAndysc** [comment]
Parser updated, please try now
