### ISSUE TITLE
[Feature] Missing Counter/ConditionValue3 usage for CONDITION_QUEST_OBJECTIVE_PROGRESS(48)

### ISSUE THREAD

**Issue by mdX7** [BAndysc/WoWDatabaseEditor#154]
**Is your feature request related to a problem? Please describe.**
CONDITION_QUEST_OBJECTIVE_PROGRESS is utilizing ConditionValue3 as counter. In the editor theres no field to actually set the value for it.

**Describe the solution you'd like**
Additional field to fill data for it

**Additional context**
![image](https://user-images.githubusercontent.com/12143653/183970858-cf78bf5a-3286-4df4-930c-594f62ceac68.png)

**Comment by BAndysc** [comment]
https://github.com/BAndysc/WoWDatabaseEditor/commit/5125b314aea7b10fd852f3f690cf79600615a262 Fixed
