### ISSUE TITLE
[Feature] Generic editors for most typical tables

### ISSUE THREAD

**Issue by BAndysc** [BAndysc/WoWDatabaseEditor#16]
## Summary

Some tables in database require special editors (like Smart Script editor is not just a database view, instead it creates abstraction layer), however a lot of other tables do NOT require special editor and can have just a generic one. For instance `spell_area` or `vehicle_template_accessory` editors can have the same generic editor, which would be just a database view.

The tables should be defined in some external file, preferably json with tables definitions, the module would read the definition and add appropriate editors to the project

**Comment by pelekon** [comment]
I will do it in 2 weeks or so
