### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by Phantoms123** [BAndysc/WoWDatabaseEditor#165]
**Describe the bug**

**Version (commit hash)**
Please include what was the WoW Database Editor version (commit hash). **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**

If you have built the binary yourself, check commit hash with `git rev-parse HEAD`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by BAndysc** [comment]
Fixed (please redownload the editor and let it update again)
