### ISSUE TITLE
WOTLK Classic

### ISSUE THREAD

**Issue by miraco** [BAndysc/WoWDatabaseEditor#171]
**Is your feature request related to a problem? Please describe.**
With wotlk classic release a ton of ppl started sniffing their questing experience on wotlk classic to recreate it to trinity/azeroth/cmangos cores.
I just noticed that the current editor cant open this sniffs/doesnt show anything when loading it.

**Describe the solution you'd like**
Editor can read WOTLK Classic sniffs (ptr/official).

**Comment by BAndysc** [comment]
The editor uses https://github.com/TrinityCore/WowPacketParser to open sniffs, but the parser now supports wotlk classic.

**Comment by r4d1sh** [comment]
> The editor uses https://github.com/TrinityCore/WowPacketParser to open sniffs, but the parser now supports wotlk classic.

It looks like WowPacketParser supports WotLK Classic, but WoWDatabaseEditor still can't open them. 3.4.x versions are not even in the list of custom builds.
