### ISSUE TITLE
Creature Template

### ISSUE THREAD

**Issue by Kurariahunter** [BAndysc/WoWDatabaseEditor#175]
I've been working with legion previously and was sad this didn't work with that database. But, that isn't the issue I'm having with this editor. I went back to the wrath version so I could script with lua ect. I knew this editor worked for 3.3.5a so I figured what the hell right? I load it up and fill out all the info. Seems to be working until I go to load stuff. I picked the right core for the build I have but seems the columns are off? I don't know that this repack has a custom table structure. I wouldn't think so but what do I know? Anyways any way I can get this working with what I have? It's a great editor and I wanna use it.

![Picker](https://user-images.githubusercontent.com/24595356/209475676-ad72e339-4007-4f2c-8f0f-106d747b5f57.jpg)
![Picker2](https://user-images.githubusercontent.com/24595356/209475677-035a0b6b-54ee-479c-97fd-18e4c7353b95.jpg)
![Picker3](https://user-images.githubusercontent.com/24595356/209475678-9042e07d-4ae4-40d7-ae16-3d9b23c7d8c9.jpg)
![Picker4](https://user-images.githubusercontent.com/24595356/209475679-4612de86-a01c-444c-93a8-13e9baa06686.jpg)
![Picker5](https://user-images.githubusercontent.com/24595356/209475680-ce8c7d28-caa8-49f7-ab2d-b066b8a4ba40.jpg)

**Comment by BAndysc** [comment]
the editor supports only open source cores
