### ISSUE TITLE
Not compatible with the last Trinitycore Update

### ISSUE THREAD

**Issue by Krutok** [BAndysc/WoWDatabaseEditor#176]
With the last TrinityCore update, the creature table has changed, now NPCs can no longer be created or edited. this affects all creature tables

![Screenshot 2023-01-11 010915](https://user-images.githubusercontent.com/47283866/211688247-ebb52a24-1787-419a-a468-b160261b50c7.jpg)

**Comment by BAndysc** [comment]
updated to latest tc version
