### ISSUE TITLE
Can't create INSERT anymore

### ISSUE THREAD

**Issue by Bestboii** [BAndysc/WoWDatabaseEditor#182]
**Describe the bug**
Since the today's update to Build 0.1.2091 i can't create any inserts. 
Before you could just enter a new ID into the search bar and you had the option to create an insert, now you can't click "accept" anymore.

**Version (commit hash)**
Build 0.1.2091

**To Reproduce**
1. Go to 'Quest Template'
2. Enter a new ID
3. You can't click 'Accept'

**Expected behavior**
Instead of updating it should create a new INSERT for the DB

**Screenshots**
https://i.imgur.com/P1P8dwZ.png
![P1P8dwZ](https://github.com/BAndysc/WoWDatabaseEditor/assets/133664883/324e547d-d959-47c4-a70b-606eb3062550)

**Comment by gonzo1247** [comment]
The problem also exists when you want to create a Creature Script for a GUID. If you type -GUID, you cannot accept it. Only entries are accepted, no more GUIDs.

**Comment by Bestboii** [comment]
Fixed with recent update Build 0.1.2093.

Thanks :)
