### ISSUE TITLE
Getting this Error and once i download the Latest update the Editor doesnt start anymore.

### ISSUE THREAD

**Issue by iFulVius** [BAndysc/WoWDatabaseEditor#184]
![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/74435677/459917aa-7935-40e5-a17c-58f42100136c)

I downloaded an Older build ( Cuz i can start those ) but once i start them up they come up with the Error code shown above.
If i then download the Latest Build Via the Updater in the editor and close it to Make use of the Updated/Downloaded Build it just gets stuck at starting and only showing the "TestWindow" shown below.

![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/74435677/dfdb2177-108a-4da0-a548-48b1ec2d82f5)

Greetings

**Comment by Dsxcore** [comment]
Were you ever able to get your editor to start after this bug? Mine was working yesterday and is now doing this as well.

**Comment by Thordekk** [comment]
same for me

**Comment by BAndysc** [comment]
Fixed, pls redownload the editor from github if you can't start it.
