### ISSUE TITLE
read spell

### ISSUE THREAD

**Issue by Krutok** [BAndysc/WoWDatabaseEditor#189]
Searching for spells in the editor is still a bit buggy, isn't it? If I want to search for my custom or Blizzard spells, it doesn't only find them when I enter the spellID directly, it also finds them. because it doesn't show the names of the spells either, so you can't search for them either.

![Screenshot 2023-07-16 014349](https://github.com/BAndysc/WoWDatabaseEditor/assets/47283866/9e72021d-d429-45f3-bdbc-719338413d12)

The icons are sometimes read incorrectly

**Comment by BAndysc** [comment]
I believe this is now fixed
