### ISSUE TITLE
[Feature] Creature template editor

### ISSUE THREAD

**Issue by BAndysc** [BAndysc/WoWDatabaseEditor#19]
## Summary

Creature template editor shouldn’t be part of [generic editors](https://github.com/BAndysc/WoWDatabaseEditor/issues/16), because the table is too big to be comfortably edited like a database.

In case of this table, it is more convenient to edit table in columns, instead of in rows:

<img width="366" alt="Zrzut ekranu 2021-01-27 o 17 10 43" src="https://user-images.githubusercontent.com/5689666/106027342-b6b26a80-60c2-11eb-9a15-e453eb17bd06.png">

Also, in case of this table, the generated SQL should be a diff between original and modified creature_template, contrary to editing generic tables which can generate delete and insert rows.

**Comment by funjoker** [comment]
Dont know if that is a good idea.
Templates should never be touched.

**Comment by BAndysc** [comment]
Of course they should, there are some columns that indeed are „static” and they were filled in the database using `SMSG_QUERY_CREATURE_RESPONSE` packet - those shouldn’t be changed as all npcs should have correct values.

But in the same table we have a lot of columns that do not have correct values. Some can be found in UPDATE_OBJECT packet, some in even other packets (e.g. you have to gossip with npc to know its gossip menu id), there are npcs that do not have those values. Let’s just mention `VehicleId`, `gossip_menu_id`, `unit_flags`, `npc_flags`… Not to mention TrinityCore own columns in creature_template like `script_name`, `ainame`, `extra_flags`…

**Comment by funjoker** [comment]
Looking forward to split the table into WDB and non WDB tables

**Comment by BAndysc** [comment]
It would be great, no doubt :) But for now, I will leave the issue opened here. Even if the table is splitted, then it is enough to remove „static” columns from the editor.
