### ISSUE TITLE
VMaNGOS

### ISSUE THREAD

**Issue by Vanheden** [BAndysc/WoWDatabaseEditor#192]
Hello would it be possible to add VMaNGOS to this? :)

https://github.com/vmangos/core

**Comment by mroreo3** [comment]
Any update on this?

**Comment by mroreo3** [comment]
<img width="928" alt="image" src="https://github.com/BAndysc/WoWDatabaseEditor/assets/63934234/74ab8cf3-3e2c-457a-8bff-311e05203dee">

**Comment by BAndysc** [comment]
VMangos is not supported, so this message is to be expected. The thing is VMangos use their own scripting system, so while adding a database support for another core is easy, adding support for their scripting system is much more work. So unless somebody wants to add it, I don't have time to do it.
