### ISSUE TITLE
WoWDatabaseEditor no longer opens.

### ISSUE THREAD

**Issue by TheSnowcraft** [BAndysc/WoWDatabaseEditor#194]
**Describe the bug**
WoW Database Editor will no longer open after an auto-update. I've noticed when I activate the .exe the number of active background processes increases by one for about a second, before returning to the prior value.

I suspect this won't be easily reproducible, given I've been no other reports of it. If relevant, I did just update to Visual Studio 2022 yesterday from version 2019.

**Version (commit hash)**
Unknown. The COMMIT_HASH file supposed to be in the downloaded binary's main folder is missing. I think it's the latest auto-update.

**To Reproduce**
Open WoWDatabaseEditor
WoWDatabaseEditor doesn't open.

**Expected behavior**
The program will open.

**Screenshots**
N/A

**Comment by Bestboii** [comment]
Same here, updated the DB Editor and now i won't open anymore.
Even if i try to open as administrator it still won't open

**Comment by BAndysc** [comment]
The issue is now fixed, but you need to redownload the release.
