### ISSUE TITLE
No longer able to open WoWDBE

### ISSUE THREAD

**Issue by grip244** [BAndysc/WoWDatabaseEditor#196]
**Describe the bug**
Unable to open WoWDBE

**Version (commit hash)**
Please include what the WoW Database Editor version (commit hash) was. **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**
2023.1 (However I can't verify that as WoWDBE never fully opens)
If you have built the binary yourself, check the commit hash with `git rev-parse HEAD.`

**To Reproduce**
1. Go to 'WoWDatabaseEditor.Windows'
2. open 'WoWDatabaseEdiotCore.Avalonia.EXE'
3. Auto Update Fresh install: yes
4. Open WoWDBE.exe again
5. Loading window appears, but nothing happens.

**Expected behavior**
1. Open WoWDBE.EXE
2. Loads
3. Opens the main window for WoWDBE

**Screenshots**
![image](https://github.com/BAndysc/WoWDatabaseEditor/assets/24600090/9da9eaa8-8ac6-4f2e-bba0-b3f02f6b3834)

**Comment by funjoker** [comment]
confirm

**Comment by funjoker** [comment]
Update: self compiled works

**Comment by BAndysc** [comment]
Oops, bad build. Released a new build which works fine (but you will have to redownload it, sorry)
