### ISSUE TITLE
Support for 6.x

### ISSUE THREAD

**Issue by Zasig** [BAndysc/WoWDatabaseEditor#200]
We're working on a WoD 6.2.x project and would like to use your Tool for our project.

Would it be hard to enable support for it?

**Comment by BAndysc** [comment]
The editor only supports open source cores, there is no any active wod project, so it can't really be added.

**Comment by Zasig** [comment]
Its an old trinitycore fork. So it would be basically an open source core.
Do you need an open github repo or do you say, nah its an old fork so no support?

**Comment by BAndysc** [comment]
Unless the fork is actively developed and gains a lot of publicity, sorry, I don't plan to add support for it.
