### ISSUE TITLE
Conditions using CONDITION_REPUTATION_RANK

### ISSUE THREAD

**Issue by Odyssey** [BAndysc/WoWDatabaseEditor#219]
**Describe the bug**
When working with conditions using CONDITION_REPUTATION_RANK, the editor uses the wrong field type and values for ConditionValue2 (Reputation Rank). 

When generating sql, it writes the index of the element in the selectabable field instead of the corresponding bitmask value. It is also not treated as a bitmask, so it's not possible to create a mask containing more than one reputation rank.

Because of that, reputation based conditions created with the editor may often be wrong (see the reproducing section).

**Version (commit hash)**
d83de4265ddfc05e3dacfd0a915aee50a010db71

**To Reproduce**
1. As an example let's use gossip_menu_id 8558 and 8560, corresponding to The Aldor and The Scryers reputation flightmasters from TBC
```SELECT * FROM conditions WHERE SourceTypeOrReferenceId=15 AND SourceGroup IN (8558,8560);```
2. Those two characters are supposed to be flightmasters for reputation ranks ```>= friendly``` with factionIds 932 and 934 respectively, and are currently only set to friendly difficulty, so when someone reaches honored, revered or exalted they cannot use the flightmaster point anymore (as the field needs to be ```conditionValue2=16|32|64|128``` bitmask value for that to happen).
3. In WowDatabaseEditor, search for gossip_menu_option for MenuId 8558 or 8560
4. Notice you cannot switch conditionValue2 (faction rank) to a mask with multiple ranks at the same time, even though the field is a bitmask.
5. Switch reputation rank to any value, accept, and check the generated sql.
6. Notice the generated value corresponds to the element index instead of the bitmask value for said rank.

**Expected behavior**
Should be able to stack multiple reputation ranks as a bitmask and should output the right values to generated sql.
Should not be described as "minimum rank" but rather "rank mask".

**Screenshots**
[TC Wiki, conditions table](https://i.imgur.com/Q8GdoDL.png)
[Condition editor for gossip_menu_option with the example above](https://i.imgur.com/fVdrcNU.png)
[SQL output generated with rank=friendly](https://i.imgur.com/2ttE3tU.png) (4 instead of 16)

**Comment by fangshun2004** [comment]
Fixed in https://github.com/BAndysc/WoWDatabaseEditor/pull/224. Shows that it has been merged into the main branch. But I don't know why the json in the source code hasn't changed

**Comment by BAndysc** [comment]
> Fixed in #224. Shows that it has been merged into the main branch. But for some unknown reason, the json in the main branch hasn't changed

The json is changed:

https://github.com/BAndysc/WoWDatabaseEditor/blob/master/WDE.Conditions/SmartData/conditions.json#L593

Is there any problem with it?

**Comment by Odyssey** [comment]
All good nowadays.
