### ISSUE TITLE
Tab picker doesn’t show tab name

### ISSUE THREAD

**Issue by BAndysc** [BAndysc/WoWDatabaseEditor#23]
## Summary

Just look:
![unknown](https://user-images.githubusercontent.com/5689666/106029080-a26f6d00-60c4-11eb-8279-15c2d3954bc1.png)

**Comment by TranceAccount** [comment]
The button is located in the top right of the main window.
Selecting a tab from this list does not appear to be working either.

**Comment by BAndysc** [comment]
Bug not present in avalonia
