### ISSUE TITLE
Remove Unit Flag / Set Unit Flag missing Action

### ISSUE THREAD

**Issue by iFulVius** [BAndysc/WoWDatabaseEditor#237]
**Describe the bug**
Not quite a Bug, but i've noticed (Long time ago actually) that the Actions "Remove Unit Flag and Set Unit Flags are missing as an Selectable Option. However i found a workaround. Explanation follows.

**Version (commit hash)**
Version "Build 2860"

**To Reproduce**
Video Attached for an example. So Obviously the Editor knows which Action i want to use. However its not a selectable option in the Actions Tab after you create an Event. hopefully this explains the issue.

**Expected behavior**
Selectable Option for the 2 Actions.

**Screenshots**

https://github.com/user-attachments/assets/74340b64-6e4f-478b-91cf-8ad0689ce917

**Comment by iFulVius** [comment]
Ah well i just noticed you dont see the Tab in the video.. i'll reupload a new one in a second.

**Comment by iFulVius** [comment]
Now if you select any Action at all you then can after change the Action ID

![image](https://github.com/user-attachments/assets/c90430be-acd1-41bc-a3f8-eac427346846)

Once you change the Action ID to the Action im talking about ( ID 18 and 19 in this case ) the Editior knows which Actions im trying to edit and shows it appropriatly but its not a selectable option in the Action Select Tab under Templates nor anywhere else.

![image](https://github.com/user-attachments/assets/94b23bab-f623-402b-94dd-39986a661f99)

![image](https://github.com/user-attachments/assets/6890bdc9-8e23-483c-854b-c86e6cd0c758)

![image](https://github.com/user-attachments/assets/35bed5bc-573e-49e8-8c8c-2146afa4be59)

Hope this helps !

**Comment by BAndysc** [comment]
Those actions no longer exist in TrinityCore, that's why you can't select them: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/SmartScripts/SmartScriptMgr.h#L478

**Comment by iFulVius** [comment]
Interesting, cuz i am using them on my Trinitycore and they work just fine. welp thanks anyways!

**Comment by BAndysc** [comment]
I guess you are using some old TC version, aren't you?

**Comment by iFulVius** [comment]
Well old as in 2022 core /shrug
