### ISSUE TITLE
Can't Connect to MOP Database

### ISSUE THREAD

**Issue by dotI0** [BAndysc/WoWDatabaseEditor#238]
**Describe the bug**
I have a MOP Trinity Core database which I can't connect to.
After the editor starts, the error message "couldn't connect to database - unknown column 't1.faction' in 'field list' appears.
There is no data loaded from the db after this message. Unfortunately, the Repack is Closed-Source and I don't know exactly which core it belongs to. I've tested all cores given in the settings of the editor, but the error occurs on all of it.

**Version (commit hash)**
2024.01 ? Where to find in the Windows-Version?

**To Reproduce**
Start Editor with my Database

**Expected behavior**
Connecting to the Database and see the Data in the Editor.

**Screenshots**
![image](https://github.com/user-attachments/assets/da17558d-eac6-494e-a049-a624af15281c)
![image](https://github.com/user-attachments/assets/20d4bb55-6625-4b09-b020-d03e52c16a26)

**Comment by dotI0** [comment]
In the 2021 Version of the Editor, the connection is working.
Game objects, Creatures, etc. are showing up.

Since the 2023 version, the connection is broken.

**Comment by BAndysc** [comment]
1. Don't use repacks, they are shit and not worth using.
2. TrinityCore has never supported MoP.
