### ISSUE TITLE
WoWDataBaseEditor doesnt connect to my Database since the last Update

### ISSUE THREAD

**Issue by iFulVius** [BAndysc/WoWDatabaseEditor#243]
**Describe the bug**

Updated the DataBaseEditor and since the Update it won't properly connect to the Database, it shows as a error in the bottom left corner errors that havent appeared before, such as that some Table's dont exist. They havent existed before the Update either, so idk why they happen now.

My WoW - Server Runs on AzerothCore and the Compability Mode is set to Azerothcore.

Any ideas why this might happen ?

**Version (commit hash)**
Please include what was the WoW Database Editor version (commit hash). **If you downloaded binary, open file COMMIT_HASH from the main folder and paste the content in the issue description**

Current Version: build 2872

**Screenshots**

![image](https://github.com/user-attachments/assets/03530480-cb3c-4f47-a081-88b286118c4a)

![image](https://github.com/user-attachments/assets/e85375d4-ec40-41de-a3c5-7995a03df50d)

**Comment by iFulVius** [comment]
Well im thinking that someone might have deleted that Table by accident and thats why it gives me the error message now, i will investigate but i guess if you have an answer that could help i'll gladly take it.

**Comment by iFulVius** [comment]
ok update,
 i think the table might be new. am not using Latest Azerothcore version unfortunately. does that mean i cant use the DataBaseEditor now anymore ?

**Comment by BAndysc** [comment]
Yes, you don't have the latest Azerothcore that's why it doesn't work. The editor supports the latest open source servers, you can't really contribute back when you don't have the latest version, so just upgrade it.
