### ISSUE TITLE
Creature Script - Error "Unknown column in 'field list'" (Build 2876)

### ISSUE THREAD

**Issue by Tyrvana** [BAndysc/WoWDatabaseEditor#244]
**Describe the bug**
Cannot save my Creature Script after the august update, prompts an error.

**Version (commit hash)** > Build 2876

**To Reproduce**
1. Update to august 23-30 patch.
2. Open specific Creature script
3. Just try to save
4. --> Unknown column 'action_param7' in 'field list'.

**Expected behavior**
Not prompt error, worked fine past 2 months while doing the entire script until i just updated the editor now, tried fixing, removing & updating the script to no avail. _(redownloaded the previous build in the meanwhile.)_

**Screenshots**
![image](https://github.com/user-attachments/assets/3ac725df-229d-4bdf-846e-83bdcc97a74a)

**Comment by Atsuumi** [comment]
Error is still there and it has been since TWW commit

**Comment by BAndysc** [comment]
This is now fixed
