### ISSUE TITLE
TC 3.3.5 / 4.3.4 Support

### ISSUE THREAD

**Issue by Clawlancer** [BAndysc/WoWDatabaseEditor#3]
Hey!

Thanks for this amazing app, i would like to ask, i saw on the Reddit page that you are working on older version compatibility, it was 8 months ago, did you managed to do some work with that?
I would like to use the app with 3.3.5 or 4.3.4 TrinityCore.

Thanks!

**Comment by BAndysc** [comment]
Hello, nice to hear from other people, that's what makes me want to continue works on it. Sadly, in the meantime I still haven't added wrath/cata support yet. I also cannot tell you when I will do it due the lack of time. In case you would like to help me with that, let me know, I can assist you :-)

**Comment by BAndysc** [comment]
3.3.5 and 4.3.4 is generally supported pretty good already, it includes: events, actions, targets, dbc and database support
