### ISSUE TITLE
[Feature] Remove multiple from Solution explorer

### ISSUE THREAD

**Issue by funjoker** [BAndysc/WoWDatabaseEditor#36]
**Is your feature request related to a problem? Please describe.**
I have opened plenty SAI scripts to view them, but when i want to close them from explorer i have to select every single one and close them.

**Describe the solution you'd like**
Make multiple scripts selectable with Shift or CTRL and then add option to close them all.
Maybe even make "DEL" key useful here

**Additional context**

**Comment by BAndysc** [comment]
Fixed in avalonia version
