### ISSUE TITLE
Support for server-side areatrigger SAI

### ISSUE THREAD

**Issue by BAndysc** [BAndysc/WoWDatabaseEditor#37]
**Describe the bug**
TrinityCore is adding new server-side areatriggers, once this PR is merged, SAI for those triggers will be available: https://github.com/TrinityCore/TrinityCore/pull/26035. It introduces a new SAI Type.

**Comment by Shauren** [comment]
New SAI types
```
SMART_SCRIPT_TYPE_AREATRIGGER_ENTITY = 11, // PK to areatrigger_template.Id && areatrigger_template.IsServerSide = false
SMART_SCRIPT_TYPE_AREATRIGGER_ENTITY_SERVERSIDE = 12,  // PK to areatrigger_template.Id && areatrigger_template.IsServerSide = true
```

**Comment by BAndysc** [comment]
https://github.com/BAndysc/WoWDatabaseEditor/commit/85f36c305d550db1b91a0ff723dc4c3220ef6b6d
