### ISSUE TITLE
[Enhancement] update-process visibility

### ISSUE THREAD

**Issue by Jinnaix** [BAndysc/WoWDatabaseEditor#58]
Issue for keeping track of things

**Is your feature request related to a problem? Please describe.**

Right now, the option to show that an update is available is hard to notice and might be overseen by most users.

**Describe the solution you'd like**

Something to make the update process more readable to users.
![image](https://user-images.githubusercontent.com/37972361/115109244-e6139d80-9f74-11eb-8089-a21da948a0ea.png)

**Additional context**

Right now, after clicking "check for updates" an available update is shown like this (downloaded an older version for showcase):
![image](https://user-images.githubusercontent.com/37972361/115109220-bf556700-9f74-11eb-87a5-b02254aaac6b.png)

**Comment by BAndysc** [comment]
In the latest version (484), the pop up shows up when there is an update, you can't skip it :). Additionally, you can enable "silent auto updates" in settings if you always want to update without being asked. Or disable auto updates completely if the pop up annoys you
