### ISSUE TITLE
Implement Database Port

### ISSUE THREAD

**Issue by favorit5503** [BAndysc/WoWDatabaseEditor#6]
Hi. Would be nice to implement database port. I tried with 127.0.0.1:3308 but it wouldnt connect.

Thank you!

**Comment by funjoker** [comment]
Belongs to: https://github.com/BAndysc/WoWDatabaseEditor.Common

**Comment by BAndysc** [comment]
Fixed in https://github.com/BAndysc/WoWDatabaseEditor.Common/commit/dc8e15c82382cb44e33ef23dc440b6d7e0ad8ba1
