### ISSUE TITLE
[Feature] SAI - Show %-chances on Script overview

### ISSUE THREAD

**Issue by Jinnaix** [BAndysc/WoWDatabaseEditor#64]
**Is your feature request related to a problem? Please describe.**
Currently no way to see %-Event chances beside opening each one and face-check them.

**Describe the solution you'd like**
Show % in the overview screen.

**Additional context**
![image](https://user-images.githubusercontent.com/37972361/116845733-fbc8ca00-abe6-11eb-9ffa-ecf8b27f6d0e.png)

**Comment by BAndysc** [comment]
Added in https://github.com/BAndysc/WoWDatabaseEditor/commit/94534a88cca567a4109a08500c18ec29380a1f6a
