### ISSUE TITLE
[Bug/Feature] Template Editor (Creature) AI Name / Script Name

### ISSUE THREAD

**Issue by Jinnaix** [BAndysc/WoWDatabaseEditor#65]
**Is your feature request related to a problem? Please describe.**
If i want to assign a Script Name to a Creature/Gameobject, i have to remove AI Name (if exist). The Editor doesn't support that right now. Eventually having a creature with AI and Script shouldn't happen.

**Describe the solution you'd like**
Inserting a Script name should let me remove AI name or do it automatically.

**Additional context**
![image](https://user-images.githubusercontent.com/37972361/116873185-8a553f80-ac17-11eb-829b-03816dcd504b.png)

![image](https://user-images.githubusercontent.com/37972361/116873203-917c4d80-ac17-11eb-9c66-2175aa846ca6.png)

**Comment by BAndysc** [comment]
Thanks for the catch, indeed it should be editable. Fixed in build 594
