### ISSUE TITLE
[Bug/Feature] Template editor Value display / copy paste

### ISSUE THREAD

**Issue by Jinnaix** [BAndysc/WoWDatabaseEditor#66]
**Is your feature request related to a problem? Please describe.**
Some fields require and show numbers separated with a dot:
![image](https://user-images.githubusercontent.com/37972361/116963395-0ba8e280-aca9-11eb-85f5-3cbe312ca414.png)

Clicking in one of these fields e.g. for copy pasting, numbers given are separated by comma:
![image](https://user-images.githubusercontent.com/37972361/116963584-896cee00-aca9-11eb-99f3-e295d2b5b903.png)

Pasting them is impossible due to above described situation.

**Describe the solution you'd like**
Would be nice to get the correct value by clicking into and taking out of the field for not having to manually write stuff down.
Or to have the editor automatically convert wrong inputs (comma to dot) in these cases.

**Comment by BAndysc** [comment]
Thanks, fixed in https://github.com/BAndysc/WoWDatabaseEditor/commit/699843752b8390750c9ceb583dca18bff570ceab
