### ISSUE TITLE
Font & Color

### ISSUE THREAD

**Issue by Quest79** [BAndysc/WoWDatabaseEditor#68]
**Is your feature request related to a problem? Please describe.**
Dark blue in dark mode is difficult to read/edit in SQL output. 

**Describe the solution you'd like**
Just being able to change one or two colors here to user defined colors would be great. Also ability to configure the font type and size here independently of the rest of the UI would be beneficial.

**Comment by BAndysc** [comment]
Colors fixed in the latest version.
