### ISSUE TITLE
Smart Action Missing: 46

### ISSUE THREAD

**Issue by Quest79** [BAndysc/WoWDatabaseEditor#71]
**Describe the bug**
Smart Action is missing. 46

**Version (commit hash)**
Build 607

**To Reproduce**

1. Add to DB to a NPC:
`INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, comment) VALUES (50000, 0, 3, 0, 9, 0, 100, 0, 0, 6, 2000, 3000, 0, 46, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Run away!');`

2. Open in editor the NPC
3. See screenshot

**Expected behavior**
I expect the tool to know about and be able to use this smart action. The action is used for special movement.

**Screenshots**
<img width="1552" alt="WoWDatabaseEditorCore Avalonia 051121 012910 3104x1527" src="https://user-images.githubusercontent.com/635094/117785598-97ff5c00-b1f9-11eb-8db2-bfaa5c831aa9.png">

**Comment by BAndysc** [comment]
Thanks, fixed in https://github.com/BAndysc/WoWDatabaseEditor/commit/e2a2beb0b191c0abee52d50f2755159383fc3c3a, already available in the latest update.
