### ISSUE TITLE
Updater Lost Its Mind

### ISSUE THREAD

**Issue by Quest79** [BAndysc/WoWDatabaseEditor#72]
**Describe the bug**
Shut down application 10 min ago. Relaunched. Met with below screenshot. No directories of any kind were changed.

**Version (commit hash)**
As of today

**Expected behavior**
1. The app to relaunch
2. Log into DB
3. Check for updates only after 1 and 2 are in order.

**Screenshots**
<img width="865" alt="ZEN2 051421 195947 3840x2160" src="https://user-images.githubusercontent.com/635094/118346368-c2019880-b4ef-11eb-815f-7025ee05416a.png">

**Comment by BAndysc** [comment]
Hmm, I am sorry, I have checked the update files and they are correct, that means most likely the update file got corrupted during the download.

For now please manually remove the file **update.zip** in the main folder, once you redownload, it should be all fine.

In the future I will add some verification if the downloaded file is correct

**Comment by BAndysc** [comment]
btw. I love the issue title 😂

**Comment by Quest79** [comment]
I pushed in a backup and let it fully update again and it seems to be working fine again.
