### ISSUE TITLE
Freely create smartscripts/ Quest scripts

### ISSUE THREAD

**Issue by T1ti** [BAndysc/WoWDatabaseEditor#79]
**Is your feature request related to a problem? Please describe.**
There is no way to script quest scripts.
Quests cripts aren't directly linked in a column in quest_tempalte or another db like for creatures, instead theya re just in the generic smart_scripts table with an ID that links it to a quest

**Describe the solution you'd like**
Being able to create samrt scripts for quests, or a "free" smart script creation mode for similars, and then an optino to choose "quest" as smart script type

**Additional context**

**Comment by BAndysc** [comment]
TC 3.3.5/AC doesn't support quest script, TC master does, so if you pick "TrinityCore Shadowlands" core in settings, "quest script" option will appear to choose from.

**Comment by T1ti** [comment]
AC does.
As I said it's "hidden", you just create a smartscript in smart_scripts with type quest and choose start or ending

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/123878670-d7b40b80-d93f-11eb-88bd-6675a89700d6.png)

**Comment by BAndysc** [comment]
Not really, those events are not used for `quest scripts`, they are used on creature/gameobject scripts, where creature/gameobject is quest giver/quest ender. 

And it is supported by the editor:
![image](https://user-images.githubusercontent.com/5689666/123881546-dfbe7c00-d93c-11eb-80cb-04ea25f085f2.png)
 
 Acore doesn't support real quest scripts, it is not used: https://github.com/azerothcore/azerothcore-wotlk/search?q=SMART_SCRIPT_TYPE_QUEST
