### ISSUE TITLE
Editor should load spells (id and comment for name) from spell_dbc

### ISSUE THREAD

**Issue by Ovahlord** [BAndysc/WoWDatabaseEditor#88]
**Describe the bug**
long story short: the editor does not recognize server side spells which are being defined in spell_dbc. There is no need to load the entire table, just the id and the comment which should contain the name.

**Version (commit hash)**
7596bc580eeef4473c99e6678c5c9079a9770a6a

**To Reproduce**
Try to make a unit cast a server side spell and see the problem reporter reports an out of range error.

**Expected behavior**
the editor should see server side spells from spell_dbc as valid spell cast ids

**Screenshots**
![image](https://user-images.githubusercontent.com/18347559/127763237-41ea4c6b-47f2-4057-8c7e-4a1fb5aab0c4.png)

**Comment by BAndysc** [comment]
Fixed in https://github.com/BAndysc/WoWDatabaseEditor/commit/781ac61f44fde198a5b65e914ee285aea46d1fbf
