### ISSUE TITLE
Connection to Database not possible

### ISSUE THREAD

**Issue by gonzo1247** [BAndysc/WoWDatabaseEditor#89]
**Describe the bug**
After Start the DatabaseEditor follow Error is show:
"Error while connectiong to database. Make sure you have correct core version in the settings; Unknown column 't1.SpellName' in 'field list'

**Version (commit hash)**
build 843 

If you have built the binary yourself, check commit hash with `git rev-parse HEAD`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by BAndysc** [comment]
What core are you using?

**Comment by gonzo1247** [comment]
oh sry, i use the "The Cataclysm Preservation Project"

**Comment by BAndysc** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/f394bd9510ad9a6753c12dcb54bbf31e4f253a8c fixed on The Cataclysm Preservation Project side, please update the core and it will work :)
