### ISSUE TITLE
Add more event_types to smart scripts

### ISSUE THREAD

**Issue by matkhl** [BAndysc/WoWDatabaseEditor#90]
Please add more event types to smart scripts (there are more than 80 listed on trinity wiki)

I recently needed the SMART_EVENT_UPDATE_OOC event_type but it was not possible to select it. There are many other event_types left.
A nice feature would be if you can search for the event_type name in the search bar and add it like that.

![Bild_2021-08-14_220445](https://user-images.githubusercontent.com/38809570/129458833-e3315217-475c-4360-aee7-3cfcfb303a39.png)

**Comment by BAndysc** [comment]
There is `SMART_EVENT_UPDATE_OOC`, but indeed it has human readable name - Every X seconds (out of combat) in this case. It is probably a good idea to allow search by its enum name (`SMART_EVENT_UPDATE_OOC`) and display enum name after selecting an item. I will make it work this way

**Comment by matkhl** [comment]
Ah my bad. Thank you, thats great!

**Comment by BAndysc** [comment]
The window shows now enum name (e.g. `SMART_EVENT_UPDATE_OOC`) and also the search is much better now, for instance 'updt ooc' will display 'SMART_EVENT_UPDATE_OOC'
