### ISSUE TITLE
Wrong field used for phaseid @ phase conditions

### ISSUE THREAD

**Issue by mdX7** [BAndysc/WoWDatabaseEditor#98]
**Describe the bug**
Wrong field used for phaseid @ phase conditions

**Version (commit hash)**
df10fab9b790ca232e9949a508f10e4e477731cf
TC-master

**To Reproduce**
1. create condition for phase_area
2. notice that phaseid is filled in `SourceEntry` field instead of `SourceGroup`

**Expected behavior**
`SourceGroup` field should be used for phaseid, `SourceEntry` is used for areaid

**Comment by BAndysc** [comment]
Are you sure it is bugged? This looks correct to me:
![image](https://user-images.githubusercontent.com/5689666/139733928-1937c82f-0ad0-40f9-9604-e2ee3e623822.png)

```
DELETE FROM `phase_area` WHERE `AreaId` = 10;
INSERT INTO `phase_area` (`AreaId`, `PhaseId`, `Comment`) VALUES
(10, 54, 'Duskwood - Gilneas Lev 10'),
(10, 101, 'Duskwood - Gilneas City Unphased Terrain Swap');
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 26) AND (`SourceEntry` IN (10));
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `Comment`) VALUES
(26, 54, 10, 0, 0, 0, 0, 0, 0, 0, 0, 'Always'),
(26, 101, 10, 0, 0, 0, 0, 0, 0, 0, 0, 'Always');
```

Phases id: `54` and `101` are in `SourceGroup`, area id `10` is in `SourceEntry`.

**Comment by mdX7** [comment]
apparently i got kinda confused here, because its nowhere stated that its areaid in the picker or here (the 5555, dummy value):
![grafik](https://user-images.githubusercontent.com/12143653/139744410-649c72e9-f3ea-4433-a7a5-1a7524b0e9f6.png)
