### ISSUE TITLE
Errors @ time fields of conversation_template & conversation_line_template

### ISSUE THREAD

**Issue by mdX7** [BAndysc/WoWDatabaseEditor#99]
**Describe the bug**
Error is caused because we recently dropped the related fields here: https://github.com/TrinityCore/TrinityCore/commit/94b14e4f6355a7bab8004dcc2ecadadbc52833de

**Version (commit hash)**
df10fab9b790ca232e9949a508f10e4e477731cf

**To Reproduce**
Start editor with tc master/shadowlands config

**Expected behavior**
No error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12143653/139727988-1eb3721f-a81d-4156-adae-54157d800fd0.png)

**Comment by BAndysc** [comment]
Thanks, removed https://github.com/BAndysc/WoWDatabaseEditor/commit/aea4a04ee8637da88b267b3e75d9fea8117e1055
